repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v2.4.0'
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: flake8
