name: Zipline CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  ZIPLINE_INSTALL_NO_TALIB: "1"
  PIP_CACHE_DIR: "pip_cache"

jobs:
  build-and-test:
    name: ${{ matrix.os }}-${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]
        name:
          - py27-oldpandas
          - py35-oldpandas
          - py35-newpandas
          - py36-newpandas
        include:
          - name: py27-oldpandas
            python-version: 2.7
            constraints-file: etc/constraints_oldpandas.txt
          - name: py35-oldpandas
            python-version: 3.5
            constraints-file: etc/constraints_oldpandas.txt
          - name: py35-newpandas
            python-version: 3.5
            constraints-file: etc/constraints_newpandas.txt
          - name: py36-newpandas
            python-version: 3.6
            constraints-file: etc/constraints_newpandas.txt

        exclude:
          # Don't run mac/windows builds for legacy targets.
          - name: py27-oldpandas
            os: macos-10.15
          - name: py27-oldpandas
            os: windows-2019

    steps:
      - name: Dump Matrix Config
        env:
          MATRIX: ${{ toJson(matrix) }}
        run: echo "$MATRIX"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Windows Build Environment.
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore Pip Cache
        uses: actions/cache@v1
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ matrix.os }}-${{ matrix.name }}-pip-${{ hashFiles('etc/constraints_*.txt') }}

      # - name: Create virtualenv
      #   run: |
      #     python -m pip install --user virtualenv
      #     python -m virtualenv -p python${{ matrix.python-version }} ~/venv
      #   shell: bash

      - name: Install dependencies in virtualenv
        run: |
          # source ~/venv/bin/activate
          bash etc/dev-install
        env:
          ZIPLINE_INSTALL_NO_TALIB: "1"
          ZIPLINE_INSTALL_CONSTRAINTS: "${{ matrix.constraints-file }}"

      - name: Pip freeze
        run: |
          # source ~/venv/bin/activate
          python -m pip freeze

      - name: Run tests
        run: |
          # source ~/venv/bin/activate
          nosetests tests
