name: Conda distribution exchange-calendars

on:
  workflow_dispatch

jobs:
  build_wheels:
    name: py${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python: [ '3.7', '3.8', '3.9' ]

    steps:
      - name: Checkout zipline-reloaded
        uses: actions/checkout@v2

      - name: Setup miniconda3
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          activate-environment: recipe
          channels: defaults, conda-forge, anaconda

      - name: conda build for ${{ matrix.os }}
        run: |
          conda activate recipe
          conda install -n recipe conda-build conda-verify anaconda-client
          conda-build --output-folder . --python ${{ matrix.python }} conda/exchange-calendars/

      - name: store macos result
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          path: osx-64/*.tar.bz2

      - name: store linux result
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          path: linux-64/*.tar.bz2

      - name: store windows result
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          path: win-64/*.tar.bz2

      - name: upload ${{ matrix.os }} result to anaconcda
        if: ${{ matrix.python != '3.9'}}
        env:
          OS: ${{ matrix.os }}
        run: |
          if [ "$OS" == "ubuntu-latest" ] ; then
            anaconda upload -l main -u ml4t linux-64/*.tar.bz2
          else
            if [ "$OS" == "macos-latest" ] ; then
              anaconda upload -l main -u ml4t osx-64/*.tar.bz2
           else
              anaconda upload -l main -u ml4t win-64/*.tar.bz2
            fi
          fi
