name: Zipline CI (Windows)

on:
  push:
    branches-ignore:
      - '**'
    # branches:
    #   - master
  pull_request:
    branches-ignore:
      - '**'
    # branches:
    #   - master

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    # - name: pip cache
    #   uses: actions/cache@v2
    #   with:
    #     path: ${{ steps.pip-cache.outputs.dir }}
    #     key: ${{ runner.os }}-pip-${{ hashFiles('etc/requirements_py36_locked.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    # - name: Install requirements
    #   run: |
    #     python -m pip install -r etc/requirements_build.in -c etc/requirements_locked.txt
    - name: Init Conda in Powershell
      run: |
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Install scientific python requirements
      run: |
        conda create -y --name test python=${{matrix.python-version}} pip pandas=0.22.0 numpy=1.19.1 scipy=1.5.0 cython=0.29.21
    - name: Install TA lib
      run: |
        conda activate test
        conda install -y -c quantopian ta-lib
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install other requirements
      run: |
        conda activate test
        pip install --no-binary=bcolz -e .[dev] -c etc/requirements_py36_locked.txt

    - name: Run tests
      run: |
        conda activate test
        nosetests tests
